### ISSUE TITLE
on refresh or redirect local storage being emptied

### ISSUE THREAD

**Issue by vachi** [kisonay/firebase-auth-example#1]
Hi are you still having this issue?
Did you resolve it?
I am still having this issue, I am using `isSignInWithEmailLink` and its the same issue, after my callback redirect, i am signed in, then i redirect to another page and its signed out.

**Comment by kisonay** [comment]
Yes, I was able to resolve the issue.

https://github.com/kisonay/firebase-auth-example/blob/initilize-auth/src/firebase.js#L33

This line was the culprit. 

Changing it to the following solved my issue:

```
export const firebaseSignOut = () => signOut(auth).catch((error) => sendError(error));
```
